[package]
name = "ws_iced"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version="0.13.1", features = ["image"]}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
surrealdb = "2.0.4"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
